<?php
if (!defined('ABSPATH')) exit;
final class ULD_V4_Drive_Hub {
 const LIBRARIES='uld_drive_teaching_libraries';
 public static function init(){add_action('admin_menu',[__CLASS__,'menus'],130);add_action('admin_init',[__CLASS__,'actions'],6);}
 public static function menus(){
  add_submenu_page('uld','Drive Hub','Drive Hub','manage_options','uld-drive-hub',[__CLASS__,'hub']);
  add_submenu_page('uld','All My Drive','All My Drive','manage_options','uld-all-drive',[__CLASS__,'all_drive']);
  add_submenu_page('uld','Teaching Libraries','Teaching Libraries','manage_options','uld-drive-libraries',[__CLASS__,'libraries']);
 }
 private static function token(){
  $t=(string)get_option('uld_google_access_token');$e=absint(get_option('uld_google_token_expires'));if($t&&$e>time())return$t;
  $r=(string)get_option('uld_google_refresh_token');if(!$r)return'';
  $x=wp_remote_post('https://oauth2.googleapis.com/token',['timeout'=>20,'body'=>['client_id'=>get_option('uld_google_client_id'),'client_secret'=>get_option('uld_google_client_secret'),'refresh_token'=>$r,'grant_type'=>'refresh_token']]);
  if(is_wp_error($x))return'';$b=json_decode(wp_remote_retrieve_body($x),true);if(empty($b['access_token']))return'';update_option('uld_google_access_token',sanitize_text_field($b['access_token']),false);update_option('uld_google_token_expires',time()+max(60,absint($b['expires_in']??3600)-60),false);return(string)$b['access_token'];
 }
 private static function get($path,$q=[]){$t=self::token();if(!$t)return new WP_Error('drive','Google Drive is not connected.');$u='https://www.googleapis.com/drive/v3/'.ltrim($path,'/');if($q)$u=add_query_arg($q,$u);$r=wp_remote_get($u,['timeout'=>25,'headers'=>['Authorization'=>'Bearer '.$t]]);if(is_wp_error($r))return$r;$b=json_decode(wp_remote_retrieve_body($r),true);$c=wp_remote_retrieve_response_code($r);return($c>=200&&$c<300)?$b:new WP_Error('drive',$b['error']['message']??'Google Drive API error');}
 private static function list_folder($folder='root'){$safe=str_replace("'","\\'",$folder);return self::get('files',['q'=>"'{$safe}' in parents and trashed = false",'fields'=>'files(id,name,mimeType,webViewLink,modifiedTime,parents,thumbnailLink)','orderBy'=>'folder,name','pageSize'=>1000]);}
 private static function libs(){return array_values(array_filter((array)get_option(self::LIBRARIES,[]),fn($x)=>is_array($x)&&!empty($x['id'])));}
 private static function save_libs($v){update_option(self::LIBRARIES,array_values($v),false);}
 private static function norm($raw){$raw=trim((string)$raw);if(preg_match('~/folders/([A-Za-z0-9_-]+)~',$raw,$m))return$m[1];return preg_replace('/[^A-Za-z0-9_-]/','',$raw);}
 public static function actions(){if(!is_admin()||!current_user_can('manage_options'))return;
  if(isset($_POST['uld_add_library'])){check_admin_referer('uld_add_library');$id=self::norm(wp_unslash($_POST['folder_id']??''));$name=sanitize_text_field(wp_unslash($_POST['folder_name']??'Teaching Library'));if($id){$l=self::libs();$exists=false;foreach($l as$x)if($x['id']===$id)$exists=true;if(!$exists)$l[]=['id'=>$id,'name'=>$name?:'Teaching Library','assignment_only'=>1];self::save_libs($l);}wp_safe_redirect(admin_url('admin.php?page=uld-drive-libraries&notice=added'));exit;}
  if(isset($_POST['uld_remove_library'])){check_admin_referer('uld_remove_library');$id=sanitize_text_field(wp_unslash($_POST['folder_id']??''));self::save_libs(array_values(array_filter(self::libs(),fn($x)=>$x['id']!==$id)));wp_safe_redirect(admin_url('admin.php?page=uld-drive-libraries&notice=removed'));exit;}
  if(isset($_POST['uld_library_assign'])){check_admin_referer('uld_library_assign');$id=sanitize_text_field(wp_unslash($_POST['folder_id']??''));$name=sanitize_text_field(wp_unslash($_POST['folder_name']??''));$kind=sanitize_key($_POST['assign_kind']??'student');$target=absint($_POST['target_id']??0);$allowed=false;foreach(self::libs()as$l)if($l['id']===$id)$allowed=true;if($allowed&&$target){if($kind==='student'){update_user_meta($target,'uld_drive_folder_id',$id);update_user_meta($target,'uld_drive_folder_name',$name);}elseif($kind==='course'&&get_post_type($target)==='uld_course'){update_post_meta($target,'uld_drive_folder_id',$id);update_post_meta($target,'uld_drive_folder_name',$name);}}wp_safe_redirect(admin_url('admin.php?page=uld-drive-libraries&notice=assigned'));exit;}
 }
 private static function tabs($active){$tabs=['uld-drive-hub'=>'Drive Hub','uld-all-drive'=>'All My Drive','uld-drive-libraries'=>'Teaching Libraries'];echo '<div class="uld-drive-tabs">';foreach($tabs as$s=>$l)echo '<a class="'.($active===$s?'is-active':'').'" href="'.esc_url(admin_url('admin.php?page='.$s)).'">'.esc_html($l).'</a>';echo '</div>';}
 public static function hub(){echo '<div class="wrap uld-wrap">';self::hero('Drive Hub','Use your entire Google Drive privately while keeping assignment limited to approved teaching folders.');self::tabs('uld-drive-hub');echo '<div class="uld-grid"><section class="uld-v4-panel"><span class="dashicons dashicons-google"></span><h2>All My Drive</h2><p>Browse your complete connected Drive as the teacher. Nothing is assigned from this area directly.</p><a class="button button-primary button-hero" href="'.esc_url(admin_url('admin.php?page=uld-all-drive')).'">Browse All My Drive</a></section><section class="uld-v4-panel"><span class="dashicons dashicons-welcome-learn-more"></span><h2>Teaching Libraries</h2><p>Approved folders only. Assign these folders to students or courses from a controlled workspace.</p><a class="button button-primary button-hero" href="'.esc_url(admin_url('admin.php?page=uld-drive-libraries')).'">Open Teaching Libraries</a></section></div></div>';}
 private static function hero($title,$sub){echo '<div class="uld-hero"><div><span class="uld-kicker">UWEBBZ DRIVE LMS</span><h1>'.esc_html($title).'</h1><p>'.esc_html($sub).'</p></div><div class="uld-status is-connected"><span class="uld-dot"></span>Google Drive</div></div>';}
 public static function all_drive(){echo '<div class="wrap uld-wrap">';self::hero('All My Drive','Private teacher view of the complete connected Google Drive. Add only selected folders to Teaching Libraries.');self::tabs('uld-all-drive');$folder=sanitize_text_field(wp_unslash($_GET['folder']??'root'));$d=self::list_folder($folder);echo '<div class="uld-v4-toolbar"><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=uld-all-drive')).'">My Drive</a><a class="button" href="'.esc_url(add_query_arg(['page'=>'uld-all-drive','folder'=>$folder],admin_url('admin.php'))).'">Refresh</a></div>';if(is_wp_error($d)){echo '<div class="notice notice-error"><p>'.esc_html($d->get_error_message()).'</p></div></div>';return;}$files=$d['files']??[];echo '<div class="uld-v4-file-grid">';foreach($files as$f){$is=$f['mimeType']==='application/vnd.google-apps.folder';echo '<article class="uld-v4-file"><div class="uld-v4-file-top"><span class="dashicons '.($is?'dashicons-category':'dashicons-media-document').'"></span><div><small>'.($is?'Folder':'File').'</small><h3>'.esc_html($f['name']).'</h3></div></div><div class="uld-v4-actions">';if($is){echo '<a class="button button-primary" href="'.esc_url(add_query_arg(['page'=>'uld-all-drive','folder'=>$f['id']],admin_url('admin.php'))).'">Open Folder</a><form method="post" style="display:inline">';wp_nonce_field('uld_add_library');echo '<input type="hidden" name="folder_id" value="'.esc_attr($f['id']).'"><input type="hidden" name="folder_name" value="'.esc_attr($f['name']).'"><button class="button" name="uld_add_library" value="1">Add to Teaching Libraries</button></form>';}elseif(!empty($f['webViewLink']))echo '<a class="button" target="_blank" rel="noopener" href="'.esc_url($f['webViewLink']).'">Preview</a>';echo '</div></article>';}echo '</div></div>';}
 public static function libraries(){echo '<div class="wrap uld-wrap">';self::hero('Teaching Libraries','Only these approved Google Drive folders can be assigned to students or courses.');self::tabs('uld-drive-libraries');if(isset($_GET['notice']))echo '<div class="notice notice-success is-dismissible"><p>'.esc_html(ucfirst(sanitize_key($_GET['notice']))).'.</p></div>';echo '<section class="uld-v4-panel"><h2>Add a Specific Folder</h2><p>Paste a Google Drive folder URL or ID, or add folders directly from All My Drive.</p><form method="post">';wp_nonce_field('uld_add_library');echo '<div class="uld-v4-field"><label>Folder URL or ID</label><input type="text" name="folder_id" required></div><div class="uld-v4-field"><label>Library Name</label><input type="text" name="folder_name" placeholder="Cybersecurity Course Library"></div><button class="button button-primary" name="uld_add_library" value="1">Add Teaching Library</button></form></section><div class="uld-v4-file-grid">';foreach(self::libs()as$l){echo '<article class="uld-v4-file"><div class="uld-v4-file-top"><span class="dashicons dashicons-lock"></span><div><small>Assignment Only Library</small><h3>'.esc_html($l['name']).'</h3></div></div><p><code>'.esc_html($l['id']).'</code></p><div class="uld-v4-actions"><a class="button" href="'.esc_url(add_query_arg(['page'=>'uld-drive-browser','folder'=>$l['id']],admin_url('admin.php'))).'">Browse Library</a><button type="button" class="button button-primary uld-v4-toggle" data-target="lib-'.esc_attr($l['id']).'">Assign</button></div><div id="lib-'.esc_attr($l['id']).'" class="uld-v4-assign-panel" hidden>';self::assign_ui($l);echo '</div><form method="post" class="uld-library-remove">';wp_nonce_field('uld_remove_library');echo '<input type="hidden" name="folder_id" value="'.esc_attr($l['id']).'"><button class="button-link-delete" name="uld_remove_library" value="1">Remove from Teaching Libraries</button></form></article>';}echo '</div></div>';}
 private static function assign_ui($l){echo '<form method="post">';wp_nonce_field('uld_library_assign');echo '<input type="hidden" name="folder_id" value="'.esc_attr($l['id']).'"><input type="hidden" name="folder_name" value="'.esc_attr($l['name']).'"><div class="uld-v4-tabs"><label><input type="radio" name="assign_kind" value="student" checked><span>Students</span></label><label><input type="radio" name="assign_kind" value="course"><span>Courses</span></label></div><div class="uld-v4-choice-grid">';foreach(get_users(['orderby'=>'display_name'])as$u)echo '<label class="uld-v4-choice"><input type="radio" name="target_id" value="'.absint($u->ID).'" required><span class="uld-v4-avatar">'.esc_html(strtoupper(substr($u->display_name?:$u->user_login,0,1))).'</span><span><strong>'.esc_html($u->display_name?:$u->user_login).'</strong><small>'.esc_html($u->user_email).'</small></span></label>';foreach(get_posts(['post_type'=>'uld_course','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'title','order'=>'ASC'])as$c)echo '<label class="uld-v4-choice uld-v4-course-choice"><input type="radio" name="target_id" value="'.absint($c->ID).'"><span class="dashicons dashicons-welcome-learn-more"></span><span><strong>'.esc_html($c->post_title).'</strong><small>Course</small></span></label>';echo '</div><button class="button button-primary" name="uld_library_assign" value="1">Assign Selected</button></form>';}
}
ULD_V4_Drive_Hub::init();
