<?php
if(!defined('ABSPATH'))exit;

// Notifications are part of the unified LMS and load with course tools.
if(!class_exists('ULD_Notifications')){
 require_once plugin_dir_path(__FILE__).'class-uld-notifications.php';
 ULD_Notifications::init();
}

final class ULD_Course_Tools{
 public static function init(){add_action('add_meta_boxes',[__CLASS__,'boxes']);add_action('save_post_uld_course',[__CLASS__,'save'],20,3);add_filter('post_row_actions',[__CLASS__,'lesson_actions'],10,2);add_action('admin_init',[__CLASS__,'duplicate']);}
 public static function boxes(){add_meta_box('uld_course_drive','Google Drive Course Folder',[__CLASS__,'box'],'uld_course','side','high');}
 public static function box($post){wp_nonce_field('uld_course_'.$post->ID,'uld_course_nonce');$id=get_post_meta($post->ID,'uld_drive_folder_id',true);$name=get_post_meta($post->ID,'uld_drive_folder_name',true);echo '<p><strong>Drive folder ID</strong><br><input class="widefat" name="uld_course_drive_id" value="'.esc_attr($id).'" placeholder="Assign from My Drive or create automatically"></p><p><strong>Folder name</strong><br><input class="widefat" name="uld_course_drive_name" value="'.esc_attr($name).'"></p><p><label><input type="checkbox" name="uld_create_course_folder" value="1"> Create a Google Drive folder for this course when I save it (only when no folder is assigned).</label></p>';if($id)echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url('https://drive.google.com/drive/folders/'.$id).'">Open Course Folder</a></p>';}
 public static function save($id,$post,$update){if(wp_is_post_revision($id)||wp_is_post_autosave($id)||!current_user_can('edit_post',$id))return;if(empty($_POST['uld_course_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['uld_course_nonce'])),'uld_course_'.$id))return;$folder=sanitize_text_field(wp_unslash($_POST['uld_course_drive_id']??''));$name=sanitize_text_field(wp_unslash($_POST['uld_course_drive_name']??''));if($folder){update_post_meta($id,'uld_drive_folder_id',$folder);update_post_meta($id,'uld_drive_folder_name',$name);}if(!$folder&&!empty($_POST['uld_create_course_folder']))self::create_folder($id,$post->post_title);}
 private static function create_folder($course_id,$title){$token=(string)get_option('uld_google_access_token');if(!$token){update_post_meta($course_id,'uld_drive_folder_status','Open My Drive to refresh the Google session, then save again.');return;}$r=wp_remote_post('https://www.googleapis.com/drive/v3/files?fields=id,name',['timeout'=>25,'headers'=>['Authorization'=>'Bearer '.$token,'Content-Type'=>'application/json; charset=UTF-8'],'body'=>wp_json_encode(['name'=>$title,'mimeType'=>'application/vnd.google-apps.folder'])]);if(is_wp_error($r))return;$code=wp_remote_retrieve_response_code($r);$b=json_decode(wp_remote_retrieve_body($r),true);if($code>=200&&$code<300&&!empty($b['id'])){update_post_meta($course_id,'uld_drive_folder_id',sanitize_text_field($b['id']));update_post_meta($course_id,'uld_drive_folder_name',sanitize_text_field($b['name']??$title));update_post_meta($course_id,'uld_drive_folder_status','Created automatically');}}
 public static function lesson_actions($actions,$post){if($post->post_type!=='uld_lesson'||!current_user_can('edit_post',$post->ID))return $actions;$url=wp_nonce_url(add_query_arg(['uld_duplicate_lesson'=>$post->ID],admin_url('edit.php?post_type=uld_lesson')),'uld_duplicate_'.$post->ID);$actions['uld_duplicate']='<a href="'.esc_url($url).'">Duplicate lesson</a>';return $actions;}
 public static function duplicate(){if(empty($_GET['uld_duplicate_lesson'])||!current_user_can('edit_posts'))return;$id=absint($_GET['uld_duplicate_lesson']);check_admin_referer('uld_duplicate_'.$id);$p=get_post($id);if(!$p||$p->post_type!=='uld_lesson')return;$new=wp_insert_post(['post_type'=>'uld_lesson','post_status'=>'draft','post_title'=>$p->post_title.' Copy','post_content'=>$p->post_content,'post_excerpt'=>$p->post_excerpt]);if($new&&!is_wp_error($new)){foreach(['uld_course_id','uld_availability','uld_available_at','uld_auto_sync','uld_drive_folder_override'] as $key){$v=get_post_meta($id,$key,true);if($v!=='')update_post_meta($new,$key,$v);}wp_safe_redirect(admin_url('post.php?post='.$new.'&action=edit'));exit;}}
}
