<?php
if (!defined('ABSPATH')) exit;
final class ULD_V5_Library_Course_Importer {
 const LIBRARIES='uld_drive_teaching_libraries';
 public static function init(){add_action('admin_menu',[__CLASS__,'menu'],202);add_action('admin_init',[__CLASS__,'actions'],22);}
 public static function menu(){add_submenu_page('uld','Build from Teaching Library','Build from Library','manage_options','uld-v5-library-importer',[__CLASS__,'page']);}
 private static function token(){$t=(string)get_option('uld_google_access_token');$e=absint(get_option('uld_google_token_expires'));if($t&&$e>time())return$t;$r=(string)get_option('uld_google_refresh_token');if(!$r)return'';$x=wp_remote_post('https://oauth2.googleapis.com/token',['timeout'=>20,'body'=>['client_id'=>get_option('uld_google_client_id'),'client_secret'=>get_option('uld_google_client_secret'),'refresh_token'=>$r,'grant_type'=>'refresh_token']]);if(is_wp_error($x))return'';$b=json_decode(wp_remote_retrieve_body($x),true);if(empty($b['access_token']))return'';update_option('uld_google_access_token',sanitize_text_field($b['access_token']),false);update_option('uld_google_token_expires',time()+max(60,absint($b['expires_in']??3600)-60),false);return(string)$b['access_token'];}
 private static function list_folder($id){$t=self::token();if(!$t)return new WP_Error('drive','Google Drive is not connected.');$safe=str_replace("'","\\'",$id);$u=add_query_arg(['q'=>"'{$safe}' in parents and trashed = false",'fields'=>'files(id,name,mimeType,webViewLink,modifiedTime)','orderBy'=>'folder,name','pageSize'=>1000],'https://www.googleapis.com/drive/v3/files');$r=wp_remote_get($u,['timeout'=>25,'headers'=>['Authorization'=>'Bearer '.$t]]);if(is_wp_error($r))return$r;$b=json_decode(wp_remote_retrieve_body($r),true);$c=wp_remote_retrieve_response_code($r);return($c>=200&&$c<300)?($b['files']??[]):new WP_Error('drive',$b['error']['message']??'Drive API error');}
 private static function libraries(){return array_values(array_filter((array)get_option(self::LIBRARIES,[]),fn($x)=>is_array($x)&&!empty($x['id'])));}
 private static function plan($lib){$root=self::list_folder($lib['id']);if(is_wp_error($root))return$root;$modules=[];$root_files=[];foreach($root as$f){if(($f['mimeType']??'')==='application/vnd.google-apps.folder'){$children=self::list_folder($f['id']);if(is_wp_error($children))$children=[];$less=[];foreach($children as$c){if(($c['mimeType']??'')==='application/vnd.google-apps.folder')continue;$less[]=['title'=>$c['name']??'Lesson','drive_id'=>$c['id']??'','mime'=>$c['mimeType']??'','link'=>$c['webViewLink']??''];}$modules[]=['title'=>$f['name']??'Module','drive_id'=>$f['id']??'','lessons'=>$less];}else{$root_files[]=['title'=>$f['name']??'Resource','drive_id'=>$f['id']??'','mime'=>$f['mimeType']??'','link'=>$f['webViewLink']??''];}}if($root_files)$modules[]=['title'=>'Course Resources','drive_id'=>$lib['id'],'lessons'=>$root_files];return['library'=>$lib,'modules'=>$modules];}
 public static function actions(){if(!is_admin()||!current_user_can('manage_options'))return;$uid=get_current_user_id();
  if(isset($_POST['uld_v5_scan_library'])){check_admin_referer('uld_v5_scan_library');$id=sanitize_text_field(wp_unslash($_POST['library_id']??''));$lib=null;foreach(self::libraries()as$l)if($l['id']===$id)$lib=$l;if(!$lib)return;$plan=self::plan($lib);if(is_wp_error($plan)){set_transient('uld_v5_lib_error_'.$uid,$plan->get_error_message(),600);wp_safe_redirect(admin_url('admin.php?page=uld-v5-library-importer&error=1'));exit;}set_transient('uld_v5_lib_plan_'.$uid,$plan,HOUR_IN_SECONDS);wp_safe_redirect(admin_url('admin.php?page=uld-v5-library-importer&preview=1'));exit;}
  if(isset($_POST['uld_v5_build_library'])){check_admin_referer('uld_v5_build_library');$plan=get_transient('uld_v5_lib_plan_'.$uid);$cid=absint($_POST['course_id']??0);if(!is_array($plan)||get_post_type($cid)!=='uld_course')return;update_post_meta($cid,'uld_drive_folder_id',$plan['library']['id']);update_post_meta($cid,'uld_drive_folder_name',$plan['library']['name']);$mi=1;foreach((array)$plan['modules']as$m){$mid=wp_insert_post(['post_type'=>'uld_module','post_status'=>'publish','post_title'=>sanitize_text_field($m['title'])]);if(!$mid||is_wp_error($mid))continue;update_post_meta($mid,'uld_course_id',$cid);update_post_meta($mid,'uld_order',$mi);update_post_meta($mid,'uld_drive_folder_id',sanitize_text_field($m['drive_id']??''));$li=1;foreach((array)$m['lessons']as$l){$content='<p>This lesson is connected to an approved Google Drive teaching resource.</p>';if(!empty($l['link']))$content.='<p><a href="'.esc_url($l['link']).'" target="_blank" rel="noopener">Open learning resource</a></p>';$lid=wp_insert_post(['post_type'=>'uld_lesson','post_status'=>'draft','post_title'=>sanitize_text_field($l['title']),'post_content'=>wp_kses_post($content)]);if($lid&&!is_wp_error($lid)){update_post_meta($lid,'uld_course_id',$cid);update_post_meta($lid,'uld_module_id',$mid);update_post_meta($lid,'uld_order',$li);update_post_meta($lid,'uld_drive_id',sanitize_text_field($l['drive_id']));update_post_meta($lid,'uld_drive_mime',sanitize_text_field($l['mime']));update_post_meta($lid,'uld_drive_link',esc_url_raw($l['link']));}$li++;}$mi++;}delete_transient('uld_v5_lib_plan_'.$uid);wp_safe_redirect(admin_url('admin.php?page=uld-v5-course-builder&course_id='.$cid.'&imported=1'));exit;}
 }
 public static function page(){$uid=get_current_user_id();$libs=self::libraries();$plan=get_transient('uld_v5_lib_plan_'.$uid);$courses=get_posts(['post_type'=>'uld_course','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'title','order'=>'ASC']);echo '<div class="wrap uld-wrap"><div class="uld-hero"><div><span class="uld-kicker">UWEBBZ LMS 5.0</span><h1>Build Course from Teaching Library</h1><p>Turn an approved Google Drive library into modules and lesson resources.</p></div><div class="uld-status is-connected"><span class="uld-dot"></span>Drive → Course</div></div>';if(isset($_GET['error'])){$e=get_transient('uld_v5_lib_error_'.$uid);echo '<div class="notice notice-error"><p>'.esc_html($e?:'Drive scan failed.').'</p></div>';}
  if(!$plan){echo '<section class="uld-v4-panel"><h2>1. Choose Teaching Library</h2><p>Only folders approved in Teaching Libraries appear here.</p><form method="post">';wp_nonce_field('uld_v5_scan_library');echo '<div class="uld-v5-library-grid">';if(!$libs)echo '<div class="uld-empty"><h3>No Teaching Libraries</h3><p>Add a specific folder first.</p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=uld-drive-libraries')).'">Teaching Libraries</a></div>';foreach($libs as$l)echo '<label class="uld-v5-library-card"><input type="radio" name="library_id" value="'.esc_attr($l['id']).'" required><span class="dashicons dashicons-category"></span><span><strong>'.esc_html($l['name']).'</strong><small>Approved Drive library</small></span></label>';echo '</div><p><button class="button button-primary button-hero" name="uld_v5_scan_library" value="1" '.disabled(!$libs,true,false).'>Scan Library Structure</button></p></form></section></div>';return;}
  echo '<section class="uld-v4-panel"><div class="uld-v5-builder-head"><div><small>DRIVE IMPORT PREVIEW</small><h2>'.esc_html($plan['library']['name']).'</h2><p>Review the detected modules and resources before creating course content.</p></div><span class="uld-v5-badge">'.count($plan['modules']).' modules</span></div><div class="uld-v5-plan">';$i=1;foreach((array)$plan['modules']as$m){echo '<article class="uld-v5-plan-module"><header><span>'.$i.'</span><div><h3>'.esc_html($m['title']).'</h3><p>'.count($m['lessons']).' lesson resources</p></div></header><ol>';foreach((array)$m['lessons']as$l)echo '<li><strong>'.esc_html($l['title']).'</strong><small>'.esc_html($l['mime']).'</small></li>';echo '</ol></article>';$i++;}echo '</div><form method="post">';wp_nonce_field('uld_v5_build_library');echo '<h3>2. Choose Course</h3><div class="uld-v4-course-grid">';foreach($courses as$c)echo '<label class="uld-v4-course-card"><input type="radio" name="course_id" value="'.absint($c->ID).'" required><span class="dashicons dashicons-welcome-learn-more"></span><span><strong>'.esc_html($c->post_title).'</strong><small>Import library here</small></span></label>';echo '</div><p><button class="button button-primary button-hero" name="uld_v5_build_library" value="1" '.disabled(!$courses,true,false).'>Build Course from Library</button></p></form></section></div>';}
}
ULD_V5_Library_Course_Importer::init();
