<?php
if (!defined('ABSPATH')) exit;
final class ULD_V5_Course_Builder {
 public static function init(){add_action('admin_menu',[__CLASS__,'menu'],200);add_action('admin_init',[__CLASS__,'actions'],20);}
 public static function menu(){add_submenu_page('uld','V5 Course Builder','V5 Course Builder','manage_options','uld-v5-course-builder',[__CLASS__,'page']);}
 public static function actions(){if(!is_admin()||!current_user_can('manage_options'))return;
  if(isset($_POST['uld_v5_add_module'])){check_admin_referer('uld_v5_add_module');$cid=absint($_POST['course_id']??0);$title=sanitize_text_field(wp_unslash($_POST['module_title']??''));if($cid&&$title&&get_post_type($cid)==='uld_course'){$id=wp_insert_post(['post_type'=>'uld_module','post_status'=>'publish','post_title'=>$title]);if($id&&!is_wp_error($id)){update_post_meta($id,'uld_course_id',$cid);update_post_meta($id,'uld_order',absint($_POST['module_order']??0));}}wp_safe_redirect(admin_url('admin.php?page=uld-v5-course-builder&course_id='.$cid));exit;}
  if(isset($_POST['uld_v5_add_lesson'])){check_admin_referer('uld_v5_add_lesson');$cid=absint($_POST['course_id']??0);$mid=absint($_POST['module_id']??0);$title=sanitize_text_field(wp_unslash($_POST['lesson_title']??''));if($cid&&$title&&get_post_type($cid)==='uld_course'){$id=wp_insert_post(['post_type'=>'uld_lesson','post_status'=>'draft','post_title'=>$title]);if($id&&!is_wp_error($id)){update_post_meta($id,'uld_course_id',$cid);if($mid)update_post_meta($id,'uld_module_id',$mid);update_post_meta($id,'uld_order',absint($_POST['lesson_order']??0));}}wp_safe_redirect(admin_url('admin.php?page=uld-v5-course-builder&course_id='.$cid));exit;}
 }
 private static function hero(){echo '<div class="uld-hero"><div><span class="uld-kicker">UWEBBZ LMS 5.0</span><h1>Visual Course Builder</h1><p>Build the curriculum as modules and lessons from one workspace.</p></div><div class="uld-status is-connected"><span class="uld-dot"></span>V5 Builder</div></div>';}
 public static function page(){echo '<div class="wrap uld-wrap">';self::hero();$courses=get_posts(['post_type'=>'uld_course','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'title','order'=>'ASC']);$cid=absint($_GET['course_id']??0);
  echo '<div class="uld-v5-course-selector">';foreach($courses as$c)echo '<a class="uld-v5-course-tile '.($cid===$c->ID?'is-active':'').'" href="'.esc_url(admin_url('admin.php?page=uld-v5-course-builder&course_id='.$c->ID)).'"><span class="dashicons dashicons-welcome-learn-more"></span><strong>'.esc_html($c->post_title).'</strong></a>';echo '<a class="uld-v5-course-tile is-new" href="'.esc_url(admin_url('post-new.php?post_type=uld_course')).'"><span class="dashicons dashicons-plus-alt2"></span><strong>New Course</strong></a></div>';
  if(!$cid){echo '<div class="uld-empty"><h2>Select a course</h2><p>Choose a course above to open its visual curriculum.</p></div></div>';return;}if(get_post_type($cid)!=='uld_course'){echo '<div class="notice notice-error"><p>Invalid course.</p></div></div>';return;}
  $mods=get_posts(['post_type'=>'uld_module','post_status'=>['publish','draft'],'numberposts'=>-1,'meta_query'=>[['key'=>'uld_course_id','value'=>$cid]],'orderby'=>['meta_value_num'=>'ASC','title'=>'ASC'],'meta_key'=>'uld_order']);
  echo '<div class="uld-v5-builder-head"><div><h2>'.esc_html(get_the_title($cid)).'</h2><p>'.esc_html(wp_trim_words(wp_strip_all_tags(get_post_field('post_content',$cid)),28)).'</p></div><div><a class="button" href="'.esc_url(admin_url('post.php?post='.$cid.'&action=edit')).'">Course Settings</a> <a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=uld-v5-ai-architect&course_id='.$cid)).'">AI Course Architect</a></div></div>';
  echo '<section class="uld-v4-panel"><h3>Add Module</h3><form method="post" class="uld-v5-inline-form">';wp_nonce_field('uld_v5_add_module');echo '<input type="hidden" name="course_id" value="'.$cid.'"><input type="text" name="module_title" placeholder="Module title" required><input type="number" name="module_order" value="'.(count($mods)+1).'" min="0"><button class="button button-primary" name="uld_v5_add_module" value="1">Add Module</button></form></section>';
  echo '<div class="uld-v5-curriculum">';foreach($mods as$m){$lessons=get_posts(['post_type'=>'uld_lesson','post_status'=>['publish','draft'],'numberposts'=>-1,'meta_query'=>[['key'=>'uld_course_id','value'=>$cid],['key'=>'uld_module_id','value'=>$m->ID]],'orderby'=>['meta_value_num'=>'ASC','title'=>'ASC'],'meta_key'=>'uld_order']);echo '<section class="uld-v5-module"><header><span class="uld-v5-handle dashicons dashicons-menu"></span><div><small>MODULE</small><h3>'.esc_html($m->post_title).'</h3></div><a href="'.esc_url(admin_url('post.php?post='.$m->ID.'&action=edit')).'">Edit</a></header><div class="uld-v5-lessons">';foreach($lessons as$l)echo '<a class="uld-v5-lesson" href="'.esc_url(admin_url('post.php?post='.$l->ID.'&action=edit')).'"><span class="dashicons dashicons-media-text"></span><span><strong>'.esc_html($l->post_title).'</strong><small>'.esc_html(ucfirst($l->post_status)).'</small></span></a>';echo '<form method="post" class="uld-v5-add-lesson">';wp_nonce_field('uld_v5_add_lesson');echo '<input type="hidden" name="course_id" value="'.$cid.'"><input type="hidden" name="module_id" value="'.$m->ID.'"><input type="text" name="lesson_title" placeholder="Add lesson title" required><input type="hidden" name="lesson_order" value="'.(count($lessons)+1).'"><button class="button" name="uld_v5_add_lesson" value="1">+ Add Lesson</button></form></div></section>';}
  echo '</div></div>';}
}
ULD_V5_Course_Builder::init();
