<?php
if (!defined('ABSPATH')) exit;
final class ULD_V5_AI_Course_Architect {
 public static function init(){add_action('admin_menu',[__CLASS__,'menu'],201);add_action('admin_init',[__CLASS__,'actions'],21);}
 public static function menu(){add_submenu_page('uld','AI Course Architect','AI Course Architect','manage_options','uld-v5-ai-architect',[__CLASS__,'page']);}
 private static function provider(){return class_exists('ULD_V4_AI_Providers')?ULD_V4_AI_Providers::provider():'openai';}
 private static function key(){return class_exists('ULD_V4_AI_Providers')?ULD_V4_AI_Providers::key():'';}
 private static function model(){return class_exists('ULD_V4_AI_Providers')?ULD_V4_AI_Providers::model():'gpt-5-mini';}
 private static function prompt($source,$title,$level){return "You are the AI Course Architect inside UWEBBZ LMS. Design a rigorous, teachable course from the instructor source material. Return ONLY valid JSON. Schema: {\"course_title\":\"...\",\"description\":\"...\",\"modules\":[{\"title\":\"...\",\"description\":\"...\",\"lessons\":[{\"title\":\"...\",\"objective\":\"...\"}]}]}. Create 4-10 modules when source depth supports it and 2-8 lessons per module. Sequence from foundational to advanced. Audience: {$level}. Preferred title: {$title}. Do not invent facts beyond the source. SOURCE:\n".wp_strip_all_tags($source);}
 private static function call_ai($prompt){$key=self::key();if(!$key)return new WP_Error('no_ai','Configure AI Providers first.');$p=self::provider();if($p==='gemini'){$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode(self::model()).':generateContent?key='.rawurlencode($key);$r=wp_remote_post($url,['timeout'=>90,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode(['contents'=>[['parts'=>[['text'=>$prompt]]]]])]);if(is_wp_error($r))return$r;$b=json_decode(wp_remote_retrieve_body($r),true);$text=$b['candidates'][0]['content']['parts'][0]['text']??'';}elseif($p==='claude'){$r=wp_remote_post('https://api.anthropic.com/v1/messages',['timeout'=>90,'headers'=>['x-api-key'=>$key,'anthropic-version'=>'2023-06-01','Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>self::model(),'max_tokens'=>8000,'messages'=>[['role'=>'user','content'=>$prompt]]])]);if(is_wp_error($r))return$r;$b=json_decode(wp_remote_retrieve_body($r),true);$text=$b['content'][0]['text']??'';}else{$r=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>90,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>self::model(),'input'=>$prompt])]);if(is_wp_error($r))return$r;$b=json_decode(wp_remote_retrieve_body($r),true);$text='';foreach((array)($b['output']??[])as$i)foreach((array)($i['content']??[])as$c)if(isset($c['text']))$text.=$c['text'];}$code=wp_remote_retrieve_response_code($r);if($code<200||$code>=300)return new WP_Error('ai_error',$b['error']['message']??'AI request failed.');$text=trim($text);if(str_starts_with($text,'```'))$text=preg_replace('/^```(?:json)?\s*|\s*```$/','',$text);$d=json_decode($text,true);return(is_array($d)&&!empty($d['modules']))?$d:new WP_Error('bad_plan','AI did not return a valid course plan.');}
 public static function actions(){if(!is_admin()||!current_user_can('manage_options'))return;$uid=get_current_user_id();
  if(isset($_POST['uld_v5_architect_generate'])){check_admin_referer('uld_v5_architect_generate');$source=wp_kses_post(wp_unslash($_POST['source_content']??''));$title=sanitize_text_field(wp_unslash($_POST['course_title']??''));$level=sanitize_text_field(wp_unslash($_POST['level']??'Intermediate'));if(trim(wp_strip_all_tags($source))==='')return;$plan=self::call_ai(self::prompt($source,$title,$level));if(is_wp_error($plan)){set_transient('uld_v5_arch_error_'.$uid,$plan->get_error_message(),600);wp_safe_redirect(admin_url('admin.php?page=uld-v5-ai-architect&error=1'));exit;}set_transient('uld_v5_course_plan_'.$uid,$plan,HOUR_IN_SECONDS);wp_safe_redirect(admin_url('admin.php?page=uld-v5-ai-architect&preview=1'));exit;}
  if(isset($_POST['uld_v5_architect_build'])){check_admin_referer('uld_v5_architect_build');$plan=get_transient('uld_v5_course_plan_'.$uid);if(!is_array($plan))return;$existing=absint($_POST['course_id']??0);if($existing&&get_post_type($existing)==='uld_course'){$cid=$existing;}else{$cid=wp_insert_post(['post_type'=>'uld_course','post_status'=>'draft','post_title'=>sanitize_text_field($plan['course_title']??'AI Course'),'post_content'=>wp_kses_post('<p>'.esc_html($plan['description']??'').'</p>')]);}if(!$cid||is_wp_error($cid))return;$mi=1;foreach((array)$plan['modules']as$m){$mid=wp_insert_post(['post_type'=>'uld_module','post_status'=>'publish','post_title'=>sanitize_text_field($m['title']??('Module '.$mi))]);if(!$mid||is_wp_error($mid))continue;update_post_meta($mid,'uld_course_id',$cid);update_post_meta($mid,'uld_order',$mi);update_post_meta($mid,'uld_module_description',sanitize_textarea_field($m['description']??''));$li=1;foreach((array)($m['lessons']??[])as$l){$lid=wp_insert_post(['post_type'=>'uld_lesson','post_status'=>'draft','post_title'=>sanitize_text_field($l['title']??('Lesson '.$li)),'post_content'=>wp_kses_post('<h2>Learning Objective</h2><p>'.esc_html($l['objective']??'').'</p>')]);if($lid&&!is_wp_error($lid)){update_post_meta($lid,'uld_course_id',$cid);update_post_meta($lid,'uld_module_id',$mid);update_post_meta($lid,'uld_order',$li);} $li++;}$mi++;}delete_transient('uld_v5_course_plan_'.$uid);wp_safe_redirect(admin_url('admin.php?page=uld-v5-course-builder&course_id='.$cid.'&built=1'));exit;}
 }
 public static function page(){$uid=get_current_user_id();$plan=get_transient('uld_v5_course_plan_'.$uid);$ready=(bool)self::key();$courses=get_posts(['post_type'=>'uld_course','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'title','order'=>'ASC']);echo '<div class="wrap uld-wrap"><div class="uld-hero"><div><span class="uld-kicker">UWEBBZ LMS 5.0</span><h1>AI Course Architect</h1><p>Turn source material into a complete course plan, review it, then build it.</p></div><div class="uld-status '.($ready?'is-connected':'is-offline').'"><span class="uld-dot"></span>'.($ready?'AI Ready':'AI Setup Required').'</div></div>';if(isset($_GET['error'])){$e=get_transient('uld_v5_arch_error_'.$uid);echo '<div class="notice notice-error"><p>'.esc_html($e?:'AI generation failed.').'</p></div>';}
  if(!$plan){echo '<section class="uld-v4-panel"><form method="post">';wp_nonce_field('uld_v5_architect_generate');echo '<h2>1. Add Source Material</h2><textarea class="uld-ai-source" name="source_content" rows="18" placeholder="Paste a book outline, chapter, manual, curriculum, notes, or training material..." required></textarea><div class="uld-ai-options"><div class="uld-v4-field"><label>Preferred Course Title</label><input type="text" name="course_title"></div><div class="uld-v4-field"><label>Audience</label><div class="uld-v4-tabs"><label><input type="radio" name="level" value="Beginner"><span>Beginner</span></label><label><input type="radio" name="level" value="Intermediate" checked><span>Intermediate</span></label><label><input type="radio" name="level" value="Advanced"><span>Advanced</span></label></div></div></div><p><button class="button button-primary button-hero" name="uld_v5_architect_generate" value="1" '.disabled(!$ready,true,false).'>✨ Generate Course Blueprint</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=uld-ai-providers')).'">AI Settings</a></p></form></section></div>';return;}
  echo '<section class="uld-v4-panel"><div class="uld-v5-builder-head"><div><small>AI BLUEPRINT</small><h2>'.esc_html($plan['course_title']??'Course').'</h2><p>'.esc_html($plan['description']??'').'</p></div><span class="uld-v5-badge">Review before build</span></div><div class="uld-v5-plan">';$i=1;foreach((array)$plan['modules']as$m){echo '<article class="uld-v5-plan-module"><header><span>'.$i.'</span><div><h3>'.esc_html($m['title']??'Module').'</h3><p>'.esc_html($m['description']??'').'</p></div></header><ol>';foreach((array)($m['lessons']??[])as$l)echo '<li><strong>'.esc_html($l['title']??'Lesson').'</strong><small>'.esc_html($l['objective']??'').'</small></li>';echo '</ol></article>';$i++;}echo '</div><form method="post">';wp_nonce_field('uld_v5_architect_build');echo '<h3>2. Build Destination</h3><div class="uld-v4-course-grid"><label class="uld-v4-course-card"><input type="radio" name="course_id" value="0" checked><span class="dashicons dashicons-plus-alt2"></span><span><strong>Create New Course</strong><small>Use AI title and description</small></span></label>';foreach($courses as$c)echo '<label class="uld-v4-course-card"><input type="radio" name="course_id" value="'.absint($c->ID).'"><span class="dashicons dashicons-welcome-learn-more"></span><span><strong>'.esc_html($c->post_title).'</strong><small>Add blueprint here</small></span></label>';echo '</div><p><button class="button button-primary button-hero" name="uld_v5_architect_build" value="1">Build Course Structure</button></p></form></section></div>';}
}
ULD_V5_AI_Course_Architect::init();
